// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/99designs/gqlgen/graphql"
)

type NewAudioShort struct {
	Title        string         `json:"title"`
	Description  string         `json:"description"`
	AudioFile    graphql.Upload `json:"audio_file"`
	AudioFileURL string         `json:"audio_file_url"`
	Category     string         `json:"category"`
	CreatorID    int            `json:"creator_id"`
}
