// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/99designs/gqlgen/graphql"
)

type NewAudioShort struct {
	Title       string         `json:"title"`
	Description string         `json:"description"`
	AudioFile   graphql.Upload `json:"audio_file"`
	Category    string         `json:"category"`
	CreatorID   int            `json:"creator_id"`
}

type UpdatedAudioShort struct {
	Title       *string         `json:"title"`
	Description *string         `json:"description"`
	AudioFile   *graphql.Upload `json:"audio_file"`
	Category    *string         `json:"category"`
}
